### ISSUE TITLE
Test Datasets

### ISSUE THREAD

**Issue by 07Agarg** [jwyang/joint-unsupervised-learning#34]
Where are the test datasets of other datasets (USPS, FRGC, YTF, etc..)
(apart from MNIST-test)?

**Comment by jwyang** [comment]
hi, @07Agarg they are in datasets folder.

**Comment by 07Agarg** [comment]
hi, @jwyang , Thanks for responding. 

datasets given in the "datasets" folder are for training purpose? You didn't use any hold-out set for validation?

**Comment by jwyang** [comment]
@07Agarg yes, for deep clustering, there is no hold-out set for validation actually. it is a bit weird though.

**Comment by 07Agarg** [comment]
Okay, thanks.
